stages:
  - build
  - test
  - deploy

variables:
  FRONTEND_DIR: "front-end"
  BACKEND_DIR: "back-end"
  DOCKER_REGISTRY: "docker.io"

# Job để build front-end (Next.js)
build_frontend:
  stage: build
  image: node:20.14.0
  script:
    - cd $FRONTEND_DIR
    - npm install
    - npm run build
  artifacts:
    paths:
      - $FRONTEND_DIR/.next
    expire_in: 1 hour

# Job để build court-services
build_court_services:
  stage: build
  image: gradle:8.10.1-jdk17
  script:
    - cd $BACKEND_DIR/court-services
    - gradle build -x test
  artifacts:
    paths:
      - $BACKEND_DIR/court-services/build/libs/*.jar
    expire_in: 1 hour

# Job để build user-services
build_user_services:
  stage: build
  image: gradle:8.10.1-jdk17
  dependencies:
    - build_court_services
  script:
    - cd $BACKEND_DIR/user-services
    - gradle build -x test
  artifacts:
    paths:
      - $BACKEND_DIR/user-services/build/libs/*.jar
    expire_in: 1 hour

# Job để build booking-services
build_booking_services:
  stage: build
  image: gradle:8.10.1-jdk17
  dependencies:
    - build_user_services
  script:
    - cd $BACKEND_DIR/booking-services
    - gradle build -x test
  artifacts:
    paths:
      - $BACKEND_DIR/booking-services/build/libs/*.jar
    expire_in: 1 hour

# Job để build api-gateway
build_api_gateway:
  stage: build
  image: gradle:8.10.1-jdk17
  dependencies:
    - build_booking_services
  script:
    - cd $BACKEND_DIR/api-gateway
    - gradle build -x test
  artifacts:
    paths:
      - $BACKEND_DIR/api-gateway/build/libs/*.jar
    expire_in: 1 hour

# Job để test front-end
test_frontend:
  stage: test
  image: node:20.14.0
  dependencies:
    - build_frontend
  script:
    - cd $FRONTEND_DIR
    - npm run test

# Job để test back-end
test_court_services:
  stage: test
  image: gradle:8.10.1-jdk17
  script:
    - cd $BACKEND_DIR/court-services
    - gradle test

test_user_services:
  stage: test
  image: gradle:8.10.1-jdk17
  script:
    - cd $BACKEND_DIR/user-services
    - gradle test

test_booking_services:
  stage: test
  image: gradle:8.10.1-jdk17
  script:
    - cd $BACKEND_DIR/booking-services
    - gradle test

test_api_gateway:
  stage: test
  image: gradle:8.10.1-jdk17
  script:
    - cd $BACKEND_DIR/api-gateway
    - gradle test

deploy:
  stage: deploy
  image: docker:20.10
  services:
    - docker:dind
  dependencies:
    - build_frontend
    - build_user_services
    - build_court_services
    - build_booking_services
    - build_api_gateway
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY

    # Deploy front-end
    - cd $FRONTEND_DIR
    - docker build -t $DOCKER_REGISTRY/quocbao44/badminton-court-management:frontend .
    - docker push $DOCKER_REGISTRY/quocbao44/badminton-court-management:frontend

    # Deploy user-services
    - cd $BACKEND_DIR/user-services
    - docker build -t $DOCKER_REGISTRY/quocbao44/badminton-court-management:user-services .
    - docker push $DOCKER_REGISTRY/quocbao44/badminton-court-management:user-services

    # Deploy court-services
    - cd $BACKEND_DIR/court-services
    - docker build -t $DOCKER_REGISTRY/quocbao44/badminton-court-management:court-service .
    - docker push $DOCKER_REGISTRY/quocbao44/badminton-court-management:court-service

    # Deploy booking-services
    - cd $BACKEND_DIR/booking-services
    - docker build -t $DOCKER_REGISTRY/quocbao44/badminton-court-management:booking-services .
    - docker push $DOCKER_REGISTRY/quocbao44/badminton-court-management:booking-services

    # Deploy api-gateway
    - cd $BACKEND_DIR/api-gateway
    - docker build -t $DOCKER_REGISTRY/quocbao44/badminton-court-management:api-gateway .
    - docker push $DOCKER_REGISTRY/quocbao44/badminton-court-management:api-gateway

  only:
    - main
