FROM gradle:8.10.1-jdk17
WORKDIR /app
COPY build.gradle settings.gradle gradlew ./
COPY gradle ./gradle
RUN gradle build --no-daemon -x test || true
EXPOSE 8083
CMD ["gradle", "bootRun", "--no-daemon"]